### PR TITLE
Release B: consolidate ObjectRegistry manifest discovery (#1133)

### LINKED ISSUE #1133: refactor(core): consolidate ObjectRegistry manifest discovery + drop redundant index
## Summary

Follow-up to the #1132 review. Collapse ObjectRegistry's four overlapping manifest-discovery paths into a single `ManifestSource` interface, and drop the redundant `classNameMap` index so there's only one canonical way to reach a registered class. Internal refactor only — the public `ObjectRegistry.*` method surface stays stable.

Release A ([#1135](https://github.com/happyvertical/smrt/pull/1135)) is now merged: every `@happyvertical/smrt-*` package self-registers its manifest at import time via a `__smrt-register__.ts` shim that calls `ObjectRegistry.registerPackageManifest()`. That's the precondition Release B builds on — once packages reliably seed `__smrtManifestCache` before their `@smrt()` decorators fire, the on-demand fs-walking paths become a fallback rather than the primary discovery strategy.

> **Plan revisions from Codex review** (see [comment](https://github.com/happyvertical/smrt/issues/1133#issuecomment-4289887745)): preserved `loadAllManifests({ manifestPaths })` as a first-class explicit-paths source, made the lookup API qualified-name/package-aware, kept the current composite priority order (Static before Embedded), added a preliminary commit that extracts a leaf `manifest/store.ts` module to break the existing `registry ↔ manifest-loader` cycle before moving helpers, and resequenced so `classNameMap` removal lands **last** after discovery parity is proven.

---

## 1. Current discovery surface (what Release B is collapsing)

Current state: **four overlapping discovery paths** distributed across two files, reading/writing **nine globalThis caches**, with **six read sites** for the `classNameMap` index.

### 1.1 Discovery entry points

| Path | File | Line | Purpose | Sync/Async |
|---|---|---|---|---|
| `registerPackageManifest(url)` | registry.ts | [1522](packages/core/src/registry.ts:1522) | Seeds `__smrtManifestCache` at package import (Release A) | sync |
| `tryLoadFromExternalPackage(className)` | registry.ts | [1229](packages/core/src/registry.ts:1229) | Walks `node_modules` to find a class's manifest; calls `registerFromManifest` | async |
| `loadAllManifests({ manifestPaths? })` | registry.ts | [1407](packages/core/src/registry.ts:1407) | Startup bulk-load of every `@happyvertical/smrt-*` manifest; **explicit-path mode** exercised by [`full-registry-integration.test.ts:72-76`](packages/core/src/__tests__/full-registry-integration.test.ts:72) | sync |
| `ensureManifestLoaded(className)` | registry.ts | [1973](packages/core/src/registry.ts:1973) | On-demand hydration before field access (issue #1005) | async |
| `discoverManifestSync(className)` | manifest-loader.ts | [888](packages/core/src/manifest/manifest-loader.ts:888) | Sync lookup used by `@smrt()` decorator at class-definition time | sync |
| `discoverManifestEntry(ctor, className)` | manifest-loader.ts | [1120](packages/core/src/manifest/manifest-loader.ts:1120) | Async lookup used by field hydration. Does **package-scoped probing** via constructor's qualified name (lines 1127-1174) before any generic scan | async |

Each of these has its own cache-seeding, cache-reading, and fs-walking logic. `discoverManifestSync` and `discoverCachedManifestSync` duplicate most of their code.

### 1.2 Sync helpers (all in `registry.ts`, duplicating `manifest-loader.ts`)

These were ported from `manifest-loader.ts` back into `registry.ts` so `registerPackageManifest` could avoid circular deps. The long-term home is a new leaf `manifest/store.ts` (see §6):

- `loadStaticManifestSyncWithNode` ([227](packages/core/src/registry.ts:227))
- `discoverCachedManifestSync` ([281](packages/core/src/registry.ts:281))
- `loadExternalManifestSyncWithNode` ([536](packages/core/src/registry.ts:536))
- `loadManifestFromPathSyncWithNode` ([590](packages/core/src/registry.ts:590))
- `resolveInstalledPackageJsonPathSync` ([358](packages/core/src/registry.ts:358))
- `resolveWorkspacePackageJsonPathSync` ([389](packages/core/src/registry.ts:389))
- `resolveWorkspaceSourceManifestPathSync` ([432](packages/core/src/registry.ts:432))
- `resolveManifestExportPathSync` ([454](packages/core/src/registry.ts:454))
- `findWorkspaceRootSync` ([332](packages/core/src/registry.ts:332))

### 1.3 globalThis manifest caches (nine, across two modules)

| Cache | Declared in | Written by | Read by |
|---|---|---|---|
| `__smrtManifestStatic` | manifest-loader.ts | `loadStaticManifestSyncWithNode` | `discoverCachedManifestSync`, `discoverManifestSync` |
| `__smrtManifestStaticLoadAttempted` | manifest-loader.ts | ditto | guards re-load |
| `__smrtManifestTest` | manifest-loader.ts | `getTestManifest` | `discoverManifestSync` (test env only) |
| `__smrtManifestTestLoadAttempted` | manifest-loader.ts | ditto | guards re-load |
| `__smrtManifestLocalTest` | manifest-loader.ts | `loadLocalTestManifestSync` | `discoverManifestSync` (test env only) |
| `__smrtManifestCache` | manifest-loader.ts | `registerPackageManifest`, `loadExternalManifestSyncWithNode` | all discovery paths |
| `__smrtSTISiblingCache` | manifest-loader.ts | STI resolution helpers | `discoverSTISiblingsSync` |
| `__smrtManifestCollisions` | manifest-loader.ts | collision-detection paths | diagnostic surface |
| `__smrtRegistryClassNameMap` | shared-state.ts | `addToClassNameMap` / `removeFromClassNameMap` | case-insensitive lookups |

### 1.4 Existing `registry ↔ manifest-loader` cycle

`manifest-loader.ts` imports `ObjectRegistry` from `../registry.js` at [line 27](packages/core/src/manifest/manifest-loader.ts:27) and calls it at two sites only:
- [482](packages/core/src/manifest/manifest-loader.ts:482) — `ObjectRegistry.getClass(className)`
- [1128](packages/core/src/manifest/manifest-loader.ts:1128) — `ObjectRegistry.getClassByConstructor(ctor)`

`registry.ts` → `class-registration.ts` → `manifest-loader.ts` → `ObjectRegistry` closes the loop. The preliminary commit in §6 breaks this by extracting a leaf module that neither end depends on `ObjectRegistry`.

### 1.5 `classNameMap` index (what Release B removes)

Eagerly-maintained lowercase-simple-name → qualified-key[] map.

**Write sites** (8 calls in `class-registration.ts`):
- [152](packages/core/src/registry/class-registration.ts:152), [154](packages/core/src/registry/class-registration.ts:154) — promotion in `upsertExistingEntry`
- [809](packages/core/src/registry/class-registration.ts:809) — new decorator registration
- [1258](packages/core/src/registry/class-registration.ts:1258), [1303](packages/core/src/registry/class-registration.ts:1303), [1307](packages/core/src/registry/class-registration.ts:1307) — manifest collision paths
- [1359](packages/core/src/registry/class-registration.ts:1359), [1377](packages/core/src/registry/class-registration.ts:1377) — new manifest registration

**Read sites** (6 in `name-resolver.ts`):
- [68](packages/core/src/registry/name-resolver.ts:68) — `getCanonicalClassName`
- [79](packages/core/src/registry/name-resolver.ts:79) — `hasClassCaseInsensitive`
- [113](packages/core/src/registry/name-resolver.ts:113) — `findClass` qualified-lookup fallback
- [136](packages/core/src/registry/name-resolver.ts:136) — `findClass` simple-name
- [200](packages/core/src/registry/name-resolver.ts:200) — `findClassStrict`
- [264](packages/core/src/registry/name-resolver.ts:264) — `qualifyExtendsName`

**Direct access in tests** (migration required):
- `test-utils.ts` [44,68-69](packages/core/src/test-utils.ts:44) — snapshot/restore
- `registry.test.ts` — `ObjectRegistry.classNameMap.clear()` in setup
- `__tests__/issue-951-qualified-keys.test.ts` — five direct `.set()` / `.get()` calls

---

## 2. Proposed `ManifestSource` interface

```typescript
// packages/core/src/manifest/sources/types.ts

/** Input for a source lookup. Package/qualified context wins over simple name. */
export interface ManifestLookupQuery {
  /** Simple class name. Always provided. */
  className: string;
  /** Package name for disambiguation. Preferred when caller has it. */
  packageName?: string;
  /** Fully qualified name (`@pkg:Class`). Takes precedence over className+packageName. */
  qualifiedName?: string;
}

/** A cached or on-demand source of manifest entries. */
export interface ManifestSource {
  /** Human-readable name for logging and diagnostics. */
  readonly name: string;

  /**
   * Synchronous lookup. Must be a cache hit or a cheap sync fs read.
   * Implementations MUST prefer qualified-name or package+className over
   * simple-name lookups when those fields are populated, matching current
   * `discoverManifestEntry()` semantics (manifest-loader.ts:1120-1174).
   */
  lookup(query: ManifestLookupQuery): ManifestEntry | undefined;

  /**
   * Enumerate every entry this source knows about.
   * Used by the `loadAllManifests` replacement and by STI sibling discovery.
   */
  entries(): Iterable<ManifestEntry>;

  /**
   * Optional async hydration from a caller-provided hint.
   * Used when a sync `lookup` misses but the caller knows a package name
   * we could try to load. Returns true if the source was populated.
   */
  hydrate?(hint: { packageName?: string; className?: string }): Promise<boolean>;
}

export interface ManifestEntry {
  className: string;
  qualifiedName?: string;
  def: SmartObjectDefinition;
  packageName?: string;
  source: string; // which ManifestSource produced this entry
}
```

### 2.1 Concrete implementations (six)

| Implementation | Wraps | Role |
|---|---|---|
| `LocalTestManifestSource` | `__smrtManifestLocalTest` | Highest priority in test env; else inert |
| `TestManifestSource` | `__smrtManifestTest` | Test env only |
| `StaticManifestSource` | `__smrtManifestStatic` | smrt-core's bundled manifest |
| `EmbeddedManifestSource` | `__smrtManifestCache` | Packages that ran `registerPackageManifest` (Release A) |
| `NodeModulesFallbackSource` | fs-walk `resolveManifestExportPathSync` etc. | Only used when all others miss; seeds `__smrtManifestCache` on hit |
| `ExplicitPathsManifestSource` | explicit `string[]` of manifest paths, loaded at construction | Powers `loadAllManifests({ manifestPaths })`; used directly by `full-registry-integration.test.ts` |

### 2.2 Composite

```typescript
export class CompositeManifestSource implements ManifestSource {
  name = 'composite';
  private readonly sources: ManifestSource[];

  constructor(sources?: ManifestSource[]) {
    this.sources = sources ?? defaultSources();
  }

  lookup(query: ManifestLookupQuery): ManifestEntry | undefined {
    for (const s of this.sources) {
      const hit = s.lookup(query);
      if (hit) return hit;
    }
    return undefined;
  }

  *entries(): Iterable<ManifestEntry> {
    const seen = new Set<string>();
    for (const s of this.sources) {
      for (const entry of s.entries()) {
        const key = entry.qualifiedName ?? entry.className;
        if (!seen.has(key)) {
          seen.add(key);
          yield entry;
        }
      }
    }
  }

  async hydrate(hint: { packageName?: string; className?: string }): Promise<boolean> {
    for (const s of this.sources) {
      if (s.hydrate && (await s.hydrate(hint))) return true;
    }
    return false;
  }
}

function defaultSources(): ManifestSource[] {
  return [
    new LocalTestManifestSource(),
    new TestManifestSource(),
    new StaticManifestSource(),
    new EmbeddedManifestSource(),
    new NodeModulesFallbackSource(),
  ];
}
```

**Priority order preserves current behavior** from `discoverCachedManifestSync` ([registry.ts:281](packages/core/src/registry.ts:281)) and `discoverManifestSync` ([manifest-loader.ts:888](packages/core/src/manifest/manifest-loader.ts:888)). Note that `StaticManifestSource` comes **before** `EmbeddedManifestSource`, matching today's order; reordering is a separate behavior change with its own tests.

### 2.3 How existing entry points delegate

| Existing entry point | New implementation |
|---|---|
| `discoverManifestSync(name)` | `compositeSource.lookup({ className: name })` |
| `discoverCachedManifestSync(name)` | `compositeSource.lookup({ className: name })` — collapses onto same call |
| `discoverManifestEntry(ctor, className)` | Use constructor → qualified name → `compositeSource.lookup({ className, qualifiedName, packageName })`; fall back to `hydrate` |
| `tryLoadFromExternalPackage(name)` | `await compositeSource.hydrate({ className: name })` + `lookup` |
| `loadAllManifests()` | `for (const entry of getDefaultComposite().entries()) registerFromManifest(entry)` |
| `loadAllManifests({ manifestPaths })` | `for (const entry of new ExplicitPathsManifestSource(paths).entries()) registerFromManifest(entry)` — explicit mode, no default composite |
| `ensureManifestLoaded(name)` | `compositeSource.hydrate` then sync `lookup` with full query |
| `registerPackageManifest(url)` | **unchanged** — writes into `EmbeddedManifestSource`'s backing cache; part of the public Release A contract |

---

## 3. `classNameMap` removal

**Strategy**: delete eager maintenance; each read site becomes an iteration over the `classes` Map with case-insensitive comparison. The `classes` Map in real SMRT apps holds low hundreds of entries — iteration is trivially fast. No lazy-cache rebuild needed; profile if it turns out to matter.

**Sequencing**: this lands in a **separate commit after the discovery abstraction parity test is green** (see §6 commit 4), so a regression in either half can be bisected cleanly.

### 3.1 Per-site replacement

| Call site | Current behavior | Replacement |
|---|---|---|
| `getCanonicalClassName(name)` [name-resolver.ts:67](packages/core/src/registry/name-resolver.ts:67) | Single O(1) map lookup, returns unambiguous qualified key | Iterate `classes`, return qualified key if exactly one case-insensitive match |
| `hasClassCaseInsensitive(name)` [name-resolver.ts:78](packages/core/src/registry/name-resolver.ts:78) | Map lookup boolean | Iterate `classes`, return on first case-insensitive match |
| `findClass(name)` [name-resolver.ts:96](packages/core/src/registry/name-resolver.ts:96) | 3-step: direct hit → classNameMap → case-insensitive iter | Same, but middle step drops to iteration |
| `findClassStrict(name)` | Same | Same |
| `qualifyExtendsName(name, pkg)` | Map lookup to resolve `extends` target | Iteration |

### 3.2 Test migration

Three tests directly touch `ObjectRegistry.classNameMap`:

- `test-utils.ts:44,68-69` — remove from `snapshotObjectRegistryState` / restore
- `registry.test.ts` — remove `ObjectRegistry.classNameMap.clear()` from setup
- `__tests__/issue-951-qualified-keys.test.ts:136,174,206,345,393` — rewrite to exercise the behavior they care about without poking the map

### 3.3 `ObjectRegistry.clear()` change

[`registry.ts:1670`](packages/core/src/registry.ts:1670) drops `ObjectRegistry.classNameMap.clear()`.

---

### Create (~450 LOC)

- `packages/core/src/manifest/store.ts` — **NEW leaf module** with globalThis cache accessors + pure fs/URL helpers, no `ObjectRegistry` dependency
- `packages/core/src/manifest/sources/types.ts` — `ManifestSource`, `ManifestEntry`, `ManifestLookupQuery`, `CompositeManifestSource`
- `packages/core/src/manifest/sources/local-test.ts` — `LocalTestManifestSource`
- `packages/core/src/manifest/sources/test.ts` — `TestManifestSource`
- `packages/core/src/manifest/sources/static.ts` — `StaticManifestSource`
- `packages/core/src/manifest/sources/embedded.ts` — `EmbeddedManifestSource`
- `packages/core/src/manifest/sources/fallback.ts` — `NodeModulesFallbackSource`
- `packages/core/src/manifest/sources/explicit-paths.ts` — `ExplicitPathsManifestSource`
- `packages/core/src/manifest/sources/index.ts` — barrel
- `packages/core/src/manifest/sources/__tests__/*.test.ts` — per-source unit tests + composite
- `packages/core/src/__tests__/manifest-discovery-parity.test.ts` — golden-snapshot parity test

### Modify

- `packages/core/src/registry.ts` (3,664 LOC → ~2,800 LOC) — delegate the four entry points onto the composite; delete the sync helpers after they move into `store.ts` and `NodeModulesFallbackSource`
- `packages/core/src/manifest/manifest-loader.ts` (1,549 → ~500 LOC) — `discoverManifestSync` / `discoverManifestEntry` delegate to composite; STI sibling helpers stay; remove duplicate sync helpers
- `packages/core/src/registry/name-resolver.ts` (432 → ~350 LOC) — drop `classNameMap` reads
- `packages/core/src/registry/class-registration.ts` (1,557 → ~1,525 LOC) — drop 8 `add/removeFromClassNameMap` calls
- `packages/core/src/registry/shared-state.ts` — drop `__smrtRegistryClassNameMap` declaration + `getClassNameMap` accessor
- `packages/core/src/registry/index.ts` — drop `getClassNameMap` / `addToClassNameMap` / `removeFromClassNameMap` re-exports
- `packages/core/src/test-utils.ts` — drop classNameMap snapshot/restore
- Three test files (see §3.2)

### Net LOC delta

- `registry.ts` loses ~860 LOC (~23% smaller)
- `manifest-loader.ts` loses ~1,050 LOC (~68% smaller)
- New `store.ts` + `sources/` add ~450 LOC
- **Total registry surface shrinks from 8,206 to ~5,700 LOC** (~30% reduction)

---

### 5.1 New tests

**`packages/core/src/manifest/sources/__tests__/manifest-sources.test.ts`** (~350 LOC)

One describe-block per implementation: `lookup(query)` with each of the three query shapes (simple, package-scoped, qualified), `entries`, `hydrate` (when present). Real fs fixtures in tmpdir for `NodeModulesFallbackSource` and `ExplicitPathsManifestSource`. Plus `CompositeManifestSource` priority-order tests and de-dup tests.

**`packages/core/src/__tests__/manifest-discovery-parity.test.ts`** (~200 LOC, new — **gates commit 3 in §6**)

Golden-snapshot parity check across the full workspace:
- Set up a tmp app with `writeScopedPackage(...)` fixtures already used in [external-runtime-hydration.test.ts](packages/core/src/__tests__/external-runtime-hydration.test.ts)
- Golden snapshot captured from `origin/main` before the refactor starts; committed alongside the test
- For each registered class under the new code path, assert `ObjectRegistry.getFields()` and `ObjectRegistry.getAllFields()` match the golden snapshot

### 5.2 Existing tests that need updating

| File | Reason |
|---|---|
| `packages/core/src/__tests__/external-runtime-hydration.test.ts` | Verify `tryLoadFromExternalPackage` delegates through composite; behavior unchanged |
| `packages/core/src/__tests__/full-registry-integration.test.ts` | Verify `loadAllManifests({ manifestPaths })` still works via `ExplicitPathsManifestSource` |
| `packages/core/src/__tests__/issue-951-qualified-keys.test.ts` | Rewrite five direct `classNameMap` manipulations |
| `packages/core/src/__tests__/issue-531-case-insensitive-stub-replacement.test.ts` | Audit for `classNameMap` assumptions |
| `packages/core/src/__tests__/issue-950-manifest-sti-collision.test.ts` | Audit |
| `packages/core/src/manifest/__tests__/manifest-loader-contract.test.ts` | Update to exercise composite instead of sync helpers |
| `packages/core/src/test-utils.ts` | Drop classNameMap from snapshot |

### 5.3 Regression bar

All of the following must pass unchanged after the refactor:
- `packages/core/src/__tests__/register-package-manifest.test.ts` (Release A)
- `packages/core/src/__tests__/external-runtime-hydration.test.ts` (Release A regression)
- `packages/core/src/__tests__/full-registry-integration.test.ts` (explicit-paths mode)
- The full `npx turbo test` run (80 tasks)

---

## 6. Sequencing & risk

**Single PR. No feature flag. Six commits.**

Rationale:
- The refactor is a behavior-preserving rewrite, not a semantic change. A feature flag doubles the surface area during the transition and delays the simplification we're doing the work for.
- Release A was a bigger, more cross-cutting change and landed without a flag on the basis of parity tests + `turbo test` coverage.
- If we discover a regression post-merge, `git revert` is clean since the refactor is self-contained.
- The golden-snapshot parity test (§5.1) is our safety net.

**Commit sequence**:

1. **Commit 1 — extract leaf `manifest/store.ts`**: Move the globalThis cache accessors and pure fs/URL helpers into a new leaf module with no `ObjectRegistry` dependency. `registry.ts` and `manifest-loader.ts` both import from it. Breaks the existing `registry ↔ manifest-loader` cycle. No behavior change; `turbo test` still green.
2. **Commit 2 — introduce `ManifestSource`**: Add `ManifestSource` interface + six implementations + `CompositeManifestSource` in `packages/core/src/manifest/sources/`. Consumes `store.ts` only. Per-source unit tests + composite tests. No call sites migrated yet.
3. **Commit 3 — delegate discovery through composite** (⚠️ parity gate): Switch `discoverManifestSync`, `discoverManifestEntry`, `tryLoadFromExternalPackage`, `ensureManifestLoaded`, `loadAllManifests` to use the composite. Land the golden-snapshot parity test here. All 80 turbo test tasks must pass.
4. **Commit 4 — remove `classNameMap`**: Delete the 8 eager-maintenance calls in `class-registration.ts`; rewrite the 6 read sites in `name-resolver.ts` to iterate; migrate three tests. Isolated commit so a regression here bisects away from the discovery abstraction.
5. **Commit 5 — delete dead helpers**: Remove the orphaned sync helpers from `registry.ts` and `manifest-loader.ts` (everything that `store.ts` and the sources now own).
6. **Commit 6 — changeset**: Patch release on `@happyvertical/smrt-core`; no consumer impact.

---

## 7. Non-goals (explicit, so reviewers don't scope-creep)

Out of scope for Release B; lives in Release C ([#1134](https://github.com/happyvertical/smrt/issues/1134)) or later:

- **Don't touch `register()`'s 11-branch collision policy** — that's Release C's decision-table rewrite
- **Don't flip `SMRT_STRICT_REGISTRY` to default on** — Release C
- **Don't retire `SMRT_SKIP_STI_REHYDRATE`** — Release C, after `inheritedFields` eager population is in
- **Don't change the diagnostic collector surface** — stable from Release A
- **Don't modify `__smrt-register__.ts` shims in any package** — stable from Release A
- **Don't reorder composite priority** — preserves current Static-before-Embedded order; any reordering is a separate behavior change with its own tests
- **Don't touch `discoverSTISiblingsSync` / `__smrtSTISiblingCache`** — orthogonal to discovery collapse

---

## Breaking?

**No.** Public `ObjectRegistry.*` methods keep their current signatures as thin delegators. `registerPackageManifest` is unchanged. `loadAllManifests({ manifestPaths })` explicit-path mode preserved via `ExplicitPathsManifestSource`. Only internal module layout moves.

## Cross-refs

- Review thread: [#1132](https://github.com/happyvertical/smrt/issues/1132)
- Release A: [#1135](https://github.com/happyvertical/smrt/pull/1135) (merged)
- Release C: [#1134](https://github.com/happyvertical/smrt/issues/1134)
- Codex plan-review feedback: [comment](https://github.com/happyvertical/smrt/issues/1133#issuecomment-4289887745)

### PR DESCRIPTION
**Pull request by willgriffin**
Closes #1133.

Internal refactor of ObjectRegistry's manifest-discovery surface. No public API change, no consumer impact. Six commits, each independently testable.

## What changed

**Commit 1 — leaf `manifest/store.ts`** (4b95acd7)
Extract the globalThis cache accessors and pure fs/URL helpers out of `registry.ts` / `class-registration.ts` into a new leaf module with no `ObjectRegistry` dependency. Breaks the historical `registry.ts → class-registration.ts → manifest-loader.ts → registry.ts` cycle that forced `registry.ts` to keep its own duplicate copies of these helpers.

**Commit 2 — `ManifestSource` abstraction** (7b5164b0)
Six concrete sources (`LocalTest`, `Test`, `Static`, `Embedded`, `NodeModulesFallback`, `ExplicitPaths`) behind a single interface + `CompositeManifestSource`. `ManifestLookupQuery` carries `packageName` / `qualifiedName` context so multi-package same-simple-name scenarios (#951) resolve correctly when the caller has package identity. Priority order matches the historical `discoverCachedManifestSync`. 15 unit tests.

**Commit 3 — delegation (parity gate)** (d0b2817f)
`discoverManifestSync` and `loadAllManifests({ manifestPaths })` route through the composite. `LocalTestManifestSource` / `TestManifestSource` gate `lookup`/`entries` on `isTestEnvironment()` to preserve production isolation. Explicit parity test at `src/manifest/sources/__tests__/discovery-parity.test.ts` covers three scenarios including the Codex P1 #2 multi-package disambiguation case.

**Commit 4 — drop `classNameMap`** (ef52cf5f)
Remove the eagerly-maintained `__smrtRegistryClassNameMap` index. `name-resolver.ts` iterates the `classes` Map with object-identity de-duplication. Eight `add/removeFromClassNameMap` call sites in `class-registration.ts` deleted; five direct `ObjectRegistry.classNameMap` manipulations in `issue-951-qualified-keys.test.ts` migrated; `test-utils.ts` snapshot updated. Removes a class of cache-sync bugs (#584, #847, #951) at negligible cost (low-hundreds of classes in realistic apps).

**Commit 5 — consolidate cache getters** (11fe2d1f)
`manifest-loader.ts`'s local `getStaticManifestCache` / `getTestManifestCache` / `getLocalTestManifestCache` / `getManifestCacheMap` become re-exports from `store.ts`. Single source of truth for manifest cache access.

**Commit 6 — changeset** (2b03a862)
Patch release on `@happyvertical/smrt-core`.

## Verification

- `npx turbo build` — 41/41 packages build clean
- `npx turbo test` — 80/80 test tasks pass
- smrt-core unit tests: 1538 pass (baseline 1520 + 18 new — 15 source unit tests + 3 parity gates)
- `full-registry-integration.test.ts:72-76` (`loadAllManifests({ manifestPaths })`) continues to work via `ExplicitPathsManifestSource` — Codex P1 #1 preserved
- `manifest-loading.spec.ts:113-144` (test-env isolation in production) preserved by sources' own `isTestEnvironment()` guards
- `issue-951-qualified-keys.test.ts` passes with migrated assertions — Codex P1 #2 invariant (multi-package same-simple-name disambiguation) held

## Reviewer feedback addressed

All four points from the [plan-review comment](https://github.com/happyvertical/smrt/issues/1133#issuecomment-4289383929) are reflected:

1. **P1 — `loadAllManifests({ manifestPaths })` preservation** → `ExplicitPathsManifestSource` is a first-class source, not a special case.
2. **P1 — qualified-name/package-aware lookup** → `ManifestLookupQuery` carries `packageName` + `qualifiedName`; `matchManifest` refuses to fall back to simple-name matches across package boundaries.
3. **P2 — composite priority preserved** → historical `LocalTest → Test → Static → Embedded → Fallback` order, with explicit non-goal covering any reordering.
4. **P2 — leaf module extracted first** → commit 1 creates `store.ts` before anything else touches the discovery surface.

## Non-goals (explicit)

- Did not touch `register()`'s 11-branch collision policy — Release C (#1134)
- Did not flip `SMRT_STRICT_REGISTRY` to default on — Release C
- Did not retire `SMRT_SKIP_STI_REHYDRATE` — Release C
- Did not touch `discoverManifestEntry` async path beyond what commit 3 required — its package-scoped probing logic remained intact; further consolidation is a follow-up, not Release B

## Test plan

- [x] Build all packages (41/41 green)
- [x] Run full test suite (80/80 tasks green, 1538 core tests green)
- [x] Verify `full-registry-integration.test.ts` explicit-paths mode
- [x] Verify `manifest-loading.spec.ts` test-env production isolation
- [x] Verify `issue-951-qualified-keys.test.ts` multi-package disambiguation
- [ ] CI run on PR branch

### CODE REVIEW

File: packages/core/src/manifest/sources/test.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+  matchManifest,
+  materializeEntry,
+} from './types.js';
+
+export class TestManifestSource implements ManifestSource {
+  readonly name = 'test';
+
+  lookup(query: ManifestLookupQuery): ManifestEntry | undefined {
+    if (!isTestEnvironment()) return undefined;
+    const manifest = getTestManifestCache();
```
Comment (willgriffin) [inline packages/core/src/manifest/sources/test.ts:25]: [P1] The new `TestManifestSource` no longer lazy-loads the core test manifest on first sync lookup.

Before this refactor, `discoverManifestSync()` called `getTestManifest()`, which loaded `test-manifest-stub.js` the first time a core test class was queried. `lookup()` now only reads `__smrtManifestTest` from cache, so the first `discoverManifestSync('QueryTestEvent')` in a clean test process returns `undefined`; the call only loads the test manifest later while collecting declared dependencies, so the second call succeeds. That regresses test-time decorator/registry paths that expect sync discovery to work on first access.

File: packages/core/src/manifest/manifest-loader.ts [hunk 2]
```diff
@@ -888,66 +875,27 @@ export function loadManifestFromPathSync(
...
-        `[manifest-loader] ✅ Found ${className} in external manifest cache`,
-      );
-      // Enrich entry with packageName from manifest if not already present
-      if (!entry.packageName && manifest.packageName) {
-        return { ...entry, packageName: manifest.packageName };
-      }
-      return entry;
+  // Steps 1-4 (local-test → test → static → embedded cache) now live in
+  // CompositeManifestSource at the exact same priority order.
+  const compositeHit = getDefaultCompositeSource().lookup({ className });
```
Comment (willgriffin) [inline packages/core/src/manifest/manifest-loader.ts]: [P1] `discoverManifestSync()` drops qualified-name context before it reaches the new source abstraction.

This call only passes `{ className }`, so a qualified lookup like `@pkg/b:Widget` loses its package hint before `matchManifest()` runs. In a local repro with cached manifests for `@pkg/a:Widget` and `@pkg/b:Widget`, `discoverManifestSync('@pkg/b:Widget')` returned package A's entry because the composite fell back to simple-name matching. We should parse qualified inputs here and populate `qualifiedName`/`packageName` before delegating to the composite.

**Comment by willgriffin** [comment]
All six review comments addressed in 75da2167:

**P1 (willgriffin) — qualified-name context lost in `discoverManifestSync`**
Fixed. `discoverManifestSync` now parses qualified names before delegating:
```ts
const query = isQualifiedName(className)
  ? (() => {
      const parsed = parseQualifiedName(className);
      return {
        className: parsed.className,
        packageName: parsed.packageName,
        qualifiedName: className,
      };
    })()
  : { className };
```
Regression test added at `discovery-parity.test.ts` — two manifests with a colliding `Widget` simple name across `@pkg/a` and `@pkg/b`, `discoverManifestSync('@pkg/b:Widget')` now correctly returns package B's manifest, not package A's.

**P1 (willgriffin + Copilot) — `TestManifestSource` lazy-load regression**
Fixed. `discoverManifestSync` now seeds both the local-test *and* the core-test caches up front in test environments (via the existing `getTestManifest()` / `loadLocalTestManifestSync()` loaders) before querying the composite. The composite's test sources remain pure cache readers, matching the design goal of source purity, while the legacy lazy-load semantics are preserved at the entry point.

**P2 (Codex) — undefined sentinel in `getLocalTestManifestCache()`**
Fixed. Return type widened from `SmartObjectManifest | null` back to `SmartObjectManifest | null | undefined`. Comment on the function now documents the three-state contract (`undefined` = never attempted, `null` = attempted and empty, value = loaded) so `discoverManifestEntry`'s lazy-load branch (`if (getLocalTestManifestCache() === undefined)`) still fires.

**Copilot — `packagesLoaded` semantic drift**
Fixed. Added a `loadedCount` getter on `ExplicitPathsManifestSource`; `loadAllManifests({ manifestPaths })` uses it. Two paths pointing at the same package now count as two, matching pre-Release-B behavior.

**Copilot — duplicate `isTestEnvironment`**
Fixed. `manifest-loader.ts`'s `isTestEnvironment` now delegates to `store.ts`'s, with the `DEBUG_TEST_ENV` logging wrapper staying local. Single source of truth.

## Verification

- 1539 core tests pass (1538 baseline + 1 new regression test for qualified-name sync lookup)
- `npx turbo test` — 80/80 tasks green
- `npx turbo build` — 41/41 green

Watching CI.
