### PR TITLE
Release C: collision-policy decision table + strict default + retire SKIP_STI_REHYDRATE (#1134)

### LINKED ISSUE #1134: refactor(core): decision-table register() + strict diagnostics default + retire rehydration flag
## Summary

Third and final release of the ObjectRegistry / SmrtObject review (parent thread: #1132). Two user-visible behavior changes + one internal cleanup:

1. **Decision-table rewrite of `register()`** in `packages/core/src/registry/class-registration.ts` — collapse the 11-branch exact-match + case-insensitive collision policy, plus `registerFromManifest`'s parallel 3-branch `resolveManifestCollision`, into a single `decideCollisionPolicy()` function with an auditable decision table.
2. **Flip `SMRT_STRICT_REGISTRY` to default-on** — the opt-in strict-mode error path added in Release A becomes the default. Opt-out via `SMRT_STRICT_REGISTRY=false`.
3. **Retire `SMRT_SKIP_STI_REHYDRATE`** — delete the env-flag opt-out added in Release A. The unconditional rehydration behavior (current default since #1131) becomes the only behavior; the flag disappears from the public surface. Further optimizing away the rehydration loop itself is deferred to a follow-up with its own regression coverage.

Both Release A ([#1135](https://github.com/happyvertical/smrt/pull/1135)) and Release B ([#1138](https://github.com/happyvertical/smrt/pull/1138)) are merged.

> **Plan revisions from Codex review** (see [comment](https://github.com/happyvertical/smrt/issues/1134#issuecomment-4290823035)):
> 1. Scope of §4 narrowed — flag deleted, rehydration loop stays; the `external-runtime-hydration.test.ts:1071-1202` stale-cache repair contract is preserved rather than regressed
> 2. `merge-manifest` policy's alias-promotion step documented as caller responsibility (stays pure in the decision function)
> 3. Decision table's invocation contract made explicit: only called when the caller has identified exactly one colliding candidate. Ambiguous simple-name matches (issue #951 coexistence) fall through without consulting the table
> 4. Diagnostic call-site count corrected from seven to six; test audit enumerated for the strict-mode flip

---

### 1.1 Exact-match path ([class-registration.ts:161-278](packages/core/src/registry/class-registration.ts:161))

| # | Condition | Action | Lines |
|---|---|---|---|
| 1 | Same constructor, re-registration | accept (`upsertExistingEntry`) | [170-173](packages/core/src/registry/class-registration.ts:170) |
| 2 | Existing is a manifest stub (`_isManifestStub === true`) | replace | [180-184](packages/core/src/registry/class-registration.ts:180) |
| 3 | Existing is external-package entry, new from same package | replace | [194-200](packages/core/src/registry/class-registration.ts:194) |
| 4 | Bundled context + existing from scoped package | accept | [210-223](packages/core/src/registry/class-registration.ts:210) |
| 5 | Same source file (module re-eval) or unavailable | accept | [228-238](packages/core/src/registry/class-registration.ts:228) |
| 6 | New class extends existing (STI child-wins) | replace | [243-251](packages/core/src/registry/class-registration.ts:243) |
| 7 | Existing class extends new (STI parent-skip) | skip | [252-258](packages/core/src/registry/class-registration.ts:252) |
| 8 | Unresolved: different constructors, different sources, no inheritance | **throw** | [265-277](packages/core/src/registry/class-registration.ts:265) |

### 1.2 Case-insensitive path ([class-registration.ts:286-394](packages/core/src/registry/class-registration.ts:286)) — parallel branches 9-11

Same logical scenarios as above but keyed on case-insensitive simple-name match. One extra branch not in the exact-match path: the pnpm-duplicate case at [314-323](packages/core/src/registry/class-registration.ts:314) — when existing has a qualified key, new is from the same package with the same case-sensitive name, and constructors differ (pnpm store copies of the same class).

### 1.3 `registerFromManifest()` parallel path ([class-registration.ts:1200-1395](packages/core/src/registry/class-registration.ts:1200))

Calls `resolveManifestCollision()` ([876-929](packages/core/src/registry/class-registration.ts:876)) which returns `'child-wins' | 'skip'`:

| # | Condition | Action |
|---|---|---|
| M1 | Same source file | skip (re-export, not real collision) |
| M2 | `objectDef.extends` points at existing | child-wins (string-based inheritance) |
| M3 | `existing.extends` points at new | skip (existing child already registered) |
| M4 | No inheritance relationship | skip (keep existing) |

Surrounding logic in `registerFromManifest` ([1225-1366](packages/core/src/registry/class-registration.ts:1225)) handles merging (same-package) vs coexistence (different-package qualified keys, issue #951) independently of `resolveManifestCollision`'s decision. Ambiguous simple-name matches (where `getCanonicalClassName()` returns undefined because multiple packages share the name) bypass this block entirely and fall straight through to the exact-key check — that behavior is preserved by Release C: the new decision table is only consulted when exactly one colliding candidate exists.

### 1.4 Helpers consumed by both paths

- `upsertExistingEntry` ([93-158](packages/core/src/registry/class-registration.ts:93)) — promotes simple-key entries to qualified keys, updates constructor/config/schema/tableName on an existing entry
- `mergeManifestIntoExistingRegistration` ([1060-1198](packages/core/src/registry/class-registration.ts:1060)) — folds manifest fields/methods/schema into an existing decorator-registered entry
- `invalidateInheritanceEntries` ([1024-1058](packages/core/src/registry/class-registration.ts:1024)) — walks `classes` and clears `inheritanceChain`/`inheritedFields`/`inheritedMethods` for any descendant of an affected class
- `getSourceFileFromStack` — for module-re-eval detection
- Bundled-context detection via hardcoded path fragments (`.svelte-kit/output/`, `/dist/`, `/build/`, `.next/`, `.nuxt/`) — appears **four times** in `register()`, another candidate for extraction into a shared helper

---

## 2. Proposed decision table

**File**: new `packages/core/src/registry/collision-policy.ts`

```typescript
export type RegistrationOrigin = 'decorator' | 'manifest';
export type MatchKind = 'exact-key' | 'case-insensitive' | 'canonical-name';
export type Policy =
  | 'accept'               // keep existing identity, update metadata via upsertExistingEntry
  | 'replace'              // drop existing, register new
  | 'merge-manifest'       // fold manifest fields into existing entry; caller MUST also
                           //   promote to the new qualified key if registrationKey differs
  | 'coexist-qualified'    // different packages, different qualified keys, both live
  | 'skip'                 // existing wins, silently ignore new
  | 'throw';               // unresolvable collision — raise error

export interface CollisionInputs {
  readonly origin: RegistrationOrigin;
  readonly matchKind: MatchKind;
  readonly sameConstructor: boolean;
  readonly sameSourceFile: boolean;
  readonly bothSourceFilesKnown: boolean;
  readonly existingIsManifestStub: boolean;
  readonly newInBundledContext: boolean;
  readonly newExtendsExisting: boolean;   // via prototype (decorator) or string `extends` (manifest)
  readonly existingExtendsNew: boolean;
  readonly samePackage: boolean;
  readonly existingIsPackageQualified: boolean;
  readonly hasNewQualifiedKey: boolean;
}

export interface PolicyDecision {
  readonly policy: Policy;
  /** Stable scenario id — matches a test row. */
  readonly scenario: string;
  /** Human-readable explanation, used for verboseLog and diagnostics. */
  readonly reason: string;
}

/**
 * Invocation contract (Codex review feedback):
 * This function is only called when the caller has identified exactly ONE
 * colliding candidate for the new registration. Callers MUST handle these
 * upstream cases themselves without invoking the table:
 *   - no colliding candidate: register new fresh
 *   - ambiguous simple name (>1 existing classes share it, in different
 *     packages): fall through to the exact-key path and allow coexistence
 *     under qualified keys. See issue #951 for the semantics being preserved.
 */
export function decideCollisionPolicy(inputs: CollisionInputs): PolicyDecision;
```

Implemented as an ordered array of `{ scenario, match: (i) => boolean, policy, reason }` rows. Each row maps 1-to-1 to a scenario test.

### 2.1 Decision table rows (most-specific first)

| Scenario ID | Match | Policy | Maps to tests |
|---|---|---|---|
| `same-constructor-reregistration` | `sameConstructor` | `accept` | (implicit, vitest re-eval) |
| `manifest-stub-replacement` | `existingIsManifestStub && !sameConstructor` | `replace` | `issue-531`, `issue-847` |
| `external-package-manifest-to-real-class` | `existingIsPackageQualified && samePackage && !sameConstructor && origin === 'decorator'` | `replace` | `issue-584` |
| `same-source-file-reeval` | `sameSourceFile` | `accept` | `issue-555` |
| `unknown-source-fallback` | `!bothSourceFilesKnown` | `accept` | (vitest edge) |
| `bundled-context-known-package` | `newInBundledContext && existingIsPackageQualified` | `accept` | (webpack/vite bundler edge) |
| `sti-child-wins` | `newExtendsExisting && !existingExtendsNew` | `replace` | `issue-950` |
| `sti-parent-skip` | `existingExtendsNew && !newExtendsExisting` | `skip` | `issue-950` |
| `pnpm-duplicate` | `samePackage && !sameConstructor && matchKind === 'case-insensitive' && hasNewQualifiedKey` | `accept` | (pnpm store edge) |
| `manifest-same-package-merge` | `origin === 'manifest' && samePackage && !existingIsManifestStub` | `merge-manifest` | `issue-951:144-200`, `issue-1000` |
| `different-packages-qualified-coexist` | `origin === 'manifest' && !samePackage && hasNewQualifiedKey && existingIsPackageQualified` | `coexist-qualified` | `issue-951` |
| (default) | everything else | `throw` | — |

**The `merge-manifest` contract** (Codex review feedback): when this policy is returned, the caller MUST (a) call `mergeManifestIntoExistingRegistration(existing, objectDef, packageName)`, then (b) if `registrationKey !== existingCanonical`, alias the existing entry under `registrationKey` via `classes.set()` + `getConstructorIndex().set()`. That second step is what `issue-951:144-200` specifically pins down. The decision function remains pure; the caller's `merge-manifest` branch is ~10 lines implementing both steps atomically.

`register()` and `registerFromManifest()` both call `decideCollisionPolicy(inputs)` after collision detection and switch on `policy`. All state mutation (constructor updates, key promotion, `mergeManifestIntoExistingRegistration` calls, `invalidateInheritanceEntries` calls) lives in the caller — the policy function is pure.

---

### 3.1 Current state

`packages/core/src/registry/diagnostics.ts:49-51`:

```typescript
function strictModeEnabled(): boolean {
  return process.env.SMRT_STRICT_REGISTRY === 'true';
}
```

Off-by-default. Flipping means: set `SMRT_STRICT_REGISTRY=false` to restore current (permissive) behavior.

### 3.2 All six `recordRegistryDiagnostic` call sites

| Severity | Code | Site | When it fires |
|---|---|---|---|
| warn | `PACKAGE_MANIFEST_NOT_FOUND` | [registry.ts:1061](packages/core/src/registry.ts:1061) | Self-registration file URL doesn't exist (common in dev/test, harmless) |
| warn | `PACKAGE_MANIFEST_INVALID_SHAPE` | [registry.ts:1075](packages/core/src/registry.ts:1075) | Manifest JSON parses but has no `objects` key |
| error | `PACKAGE_MANIFEST_READ_FAILED` | [registry.ts:1088](packages/core/src/registry.ts:1088) | `registerPackageManifest(url)` fs.readFile/JSON.parse throws |
| error | `MANIFEST_EXPORT_INVALID` | [store.ts:398](packages/core/src/manifest/store.ts:398) | Package's `exports["./manifest"]` entry has no `import`/`default`/`require` path |
| error | `MANIFEST_EXPORT_NOT_JSON` | [store.ts:413](packages/core/src/manifest/store.ts:413) | Export path doesn't end in `.json` |
| error | `MANIFEST_EXPORT_NOT_FOUND` | [store.ts:438](packages/core/src/manifest/store.ts:438) | Package.json declares a manifest export but the file is missing |

The two `'warn'`-severity codes are **not** affected — warn-level diagnostics never throw even under strict mode. Only the four `'error'` codes change behavior under the flip.

### 3.3 Migration for consumers hitting these

Each error represents a real misconfiguration the consumer should fix. For anyone mid-migration: set `SMRT_STRICT_REGISTRY=false` in `.env` / CI config / test setup.

### 3.4 Test migration

`register-package-manifest.test.ts` has tests that exercise error-severity paths and expect `{ loaded: false, objectsRegistered: 0 }` as the return shape rather than a throw. Audit:

- **`silently no-ops when the manifest is malformed JSON`** — exercises `PACKAGE_MANIFEST_READ_FAILED` (error). Needs `vi.stubEnv('SMRT_STRICT_REGISTRY', 'false')` or rewritten to expect a throw.
- `silently no-ops when the manifest file is missing` — exercises `PACKAGE_MANIFEST_NOT_FOUND` (warn, unchanged).
- `silently no-ops when the manifest has no objects key` — exercises `PACKAGE_MANIFEST_INVALID_SHAPE` (warn, unchanged).

Only the malformed-JSON case needs the opt-out.

---

### 4.1 Code to delete (scope revised per Codex)

[`object.ts:1134-1172`](packages/core/src/object.ts:1134) branches on `process.env.SMRT_SKIP_STI_REHYDRATE === 'true'`. The two branches:

- **Default path** — unconditional rehydration of every STI class in the hierarchy on every save. This is what PR #1131 added, and what the test at [`external-runtime-hydration.test.ts:1071-1202`](packages/core/src/__tests__/external-runtime-hydration.test.ts:1071) pins down (it manually seeds a stale-but-present `inheritedFields` and verifies save() repairs it).
- **Opt-out path** — conservative hydration: only descendants whose `inheritedFields` is currently `undefined`.

**Release C change**: delete the env check and the opt-out branch. Keep the default unconditional rehydration as the only behavior. The file shrinks from 38 lines to ~10.

```typescript
if (tableStrategy === 'sti') {
  // Release C (#1134) retired the SMRT_SKIP_STI_REHYDRATE opt-out. PR #1131's
  // unconditional rehydration stays the single behavior: it repairs stale-but-
  // present `inheritedFields` caches (external-runtime-hydration.test.ts:1071)
  // which the conservative path would skip.
  const classesNeedingFreshSTIFieldState = Array.from(
    new Set([className, ...getSTIHierarchyMembers(className)]),
  );
  for (const stiClassName of classesNeedingFreshSTIFieldState) {
    await ObjectRegistry.getAllFields(stiClassName);
  }
}
```

### 4.2 What's explicitly NOT in scope for Release C

The perf optimization (replace the rehydration loop with eager invalidation on re-registration, so save() doesn't touch every descendant) is a **follow-up** — it needs its own regression test that proves no code path can leave `inheritedFields` stale-but-present, which is real work beyond the "retire the flag" framing of Release C. Tracked as a separate issue after Release C lands.

---

### Create (~400 LOC)

- `packages/core/src/registry/collision-policy.ts` — `CollisionInputs`, `Policy`, `PolicyDecision`, `decideCollisionPolicy`, per-scenario exports for test coverage
- `packages/core/src/registry/__tests__/collision-policy.test.ts` — one `it()` per scenario row + default-case
- `packages/core/src/__tests__/strict-registry-default.test.ts` — verify default-throw + opt-out-via-env restores warn-only behavior

### Modify

- `packages/core/src/registry/class-registration.ts` — refactor `register()` (lines 86-391) and `registerFromManifest()` (lines 1200-1395) to compute `CollisionInputs` and switch on `decideCollisionPolicy()` output; delete `resolveManifestCollision()` (876-929) — absorbed into the table (~-200 LOC net)
- `packages/core/src/registry/diagnostics.ts` — flip `strictModeEnabled()` default; update docstring (lines 14-17) that says "Release A ships this as passive" (~5 LOC)
- `packages/core/src/object.ts` — delete lines 1143-1163 (the `skipRehydrate` branch + env check); keep unconditional rehydration from lines 1164-1171 (~-30 LOC)
- `packages/core/src/registry.ts` — update `registerPackageManifest` docstring comment (line 1139) that says "Set `SMRT_STRICT_REGISTRY=true` to make …" — it's on by default now
- `packages/core/src/__tests__/register-package-manifest.test.ts` — add `vi.stubEnv('SMRT_STRICT_REGISTRY', 'false')` to the malformed-JSON test (§3.4)

**Net**: +200 LOC (new decision table + tests), -230 LOC (deleted branches + resolveManifestCollision). Net delta roughly flat; the value is in collapse and clarity.

---

### 6.1 Collision-policy unit tests

One `it()` per decision-table row, asserting `policy` and `scenario`. Pure-function tests: no registry side effects, just input/output.

### 6.2 Parity via existing integration tests (⚠️ gate)

Must stay green after commits 2-3: `issue-531`, `issue-555`, `issue-584`, `issue-847`, `issue-950`, `issue-951`, `issue-1000`. If any break, the decision table does not faithfully reproduce today's behavior — block on fixing before moving forward.

### 6.3 Strict-mode opt-out

New test file verifying:
- Default: malformed manifest → `registerPackageManifest()` throws with diagnostic code in message
- `SMRT_STRICT_REGISTRY=false` via `vi.stubEnv`: same input returns `{ loaded: false, objectsRegistered: 0 }` + records diagnostic for later flush

### 6.4 STI rehydration — regression bar only

No new tests. `external-runtime-hydration.test.ts:1071-1202` and the rest of that file are the regression net. Commit 4 must not break them.

---

## 7. Breaking changes

| Change | User impact | Migration |
|---|---|---|
| `SMRT_STRICT_REGISTRY` default on | Apps with malformed manifest exports throw during package import instead of logging. | Fix the manifest OR set `SMRT_STRICT_REGISTRY=false`. |
| `SMRT_SKIP_STI_REHYDRATE` removed | Consumers setting this flag to `'true'` lose the opt-out. Since the flag's opt-in behavior was "do less work," losing it means slightly more save-time rehydration (pre-Release-A behavior was the same). No correctness change. | None needed. |
| Error message text on collisions | Format changes slightly; now includes scenario id from the decision table. | None — text is informational. |
| `resolveManifestCollision` export removed | Any downstream consumer importing it directly from `'@happyvertical/smrt-core'` | Import is internal; no public API consumers expected. Changeset will note. |

**Minor release**. No public API method signatures change. `ObjectRegistry.*` stays stable.

---

## 8. Commit sequence (6 commits, parity gate at #3)

1. **collision-policy module + unit tests** — new file + all per-scenario tests; no call sites yet. All existing tests still pass.
2. **Route `register()` through `decideCollisionPolicy`** — compute `CollisionInputs` at the top, delete the 11-branch tree, switch on the result. ⚠️ **parity gate** — all pre-existing collision tests (`issue-531`, `issue-555`, `issue-584`, `issue-847`, `issue-950`, `issue-951`) must stay green.
3. **Route `registerFromManifest` + delete `resolveManifestCollision`** — same treatment for the manifest path, with the documented `merge-manifest` caller contract (call `mergeManifestIntoExistingRegistration` then conditionally alias). ⚠️ **parity gate** — full `turbo test` must stay green.
4. **Retire `SMRT_SKIP_STI_REHYDRATE`** — delete the env branch in `object.ts`; keep the unconditional rehydration loop. `external-runtime-hydration.test.ts` stays green unmodified.
5. **Flip `SMRT_STRICT_REGISTRY` default** — change `strictModeEnabled()` to return `process.env.SMRT_STRICT_REGISTRY !== 'false'`. Add the opt-out test. Update the one affected test in `register-package-manifest.test.ts` with `vi.stubEnv`.
6. **Changeset** — minor release on `@happyvertical/smrt-core`; enumerate breaking surface from §7.

---

## 9. Non-goals (explicit)

- Don't touch the `ManifestSource` abstraction (Release B output, stable)
- Don't change `registerPackageManifest`'s API (Release A contract, stable)
- Don't remove `classNameMap` iteration fallback (Release B already did this)
- Don't change diagnostic severities — only the default behavior on `'error'` changes
- Don't restructure `invalidateInheritanceEntries` — the existing implementation is correct
- **Don't remove the STI rehydration loop itself** (scope revision: flag goes, loop stays; perf optimization is a separate follow-up)

## Cross-refs

- Parent review: #1132
- Release A: [#1135](https://github.com/happyvertical/smrt/pull/1135) (merged)
- Release B: [#1138](https://github.com/happyvertical/smrt/pull/1138) (merged)
- Codex plan-review feedback: [comment](https://github.com/happyvertical/smrt/issues/1134#issuecomment-4290823035)

### PR DESCRIPTION
**Pull request by willgriffin**
Closes #1134. Third and final release of the [#1132 review](https://github.com/happyvertical/smrt/issues/1132) thread. Six commits, parity gates at commits 2 and 3.

## What changed

**Commit 1 — `collision-policy` module** ([5cb949e5](https://github.com/happyvertical/smrt/pull/new/refactor/issue-1134-collision-policy-strict-default/commits/5cb949e5))
New `packages/core/src/registry/collision-policy.ts` with a 16-row decision table + pure `decideCollisionPolicy(inputs)`. Every row names a scenario that maps 1:1 to an existing collision test (`issue-531`, `issue-555`, `issue-584`, `issue-847`, `issue-950`, `issue-951`, `issue-1000`). 23 unit tests cover every row plus ordering precedence.

**Commit 2 — Route `register()` through the table (parity gate)** ([a2c146b1](https://github.com/happyvertical/smrt/pull/new/refactor/issue-1134-collision-policy-strict-default/commits/a2c146b1))
The 11-branch exact-match + case-insensitive collision tree in `register()` (~300 LOC) collapses onto `applyRegisterCollisionPolicy(args)`. All state mutation stays in the caller; the policy function is pure. Full core suite + turbo 80/80 still green.

**Commit 3 — Route `registerFromManifest`, delete `resolveManifestCollision` (parity gate)** ([2c24b11c](https://github.com/happyvertical/smrt/pull/new/refactor/issue-1134-collision-policy-strict-default/commits/2c24b11c))
Same treatment for the manifest path. The `merge-manifest` caller contract is implemented end-to-end — `mergeManifestIntoExistingRegistration` followed by conditional key aliasing when the new qualified key differs from the canonical one. Preserves `issue-951:144-200` (qualified-key promotion during merge). `resolveManifestCollision` deleted.

Two decision-table refinements caught by the parity gate:
1. `manifest-stub-replacement` is now `origin === 'decorator'` only. Stub replacement never fired in `resolveManifestCollision` pre-C.
2. `manifest-same-package-merge` also fires when `existingHasNoPackage && hasNewQualifiedKey` — covers the issue-951 scenario where a bare source registration is promoted to a qualified key by an arriving manifest.

**Commit 4 — Retire `SMRT_SKIP_STI_REHYDRATE`** ([f7a11d10](https://github.com/happyvertical/smrt/pull/new/refactor/issue-1134-collision-policy-strict-default/commits/f7a11d10))
Flag deleted. Per Codex's review of the plan, the rehydration loop stays — the `external-runtime-hydration.test.ts:1071` stale-cache repair contract is preserved. Optimizing the loop away via eager invalidation is tracked in [#1139](https://github.com/happyvertical/smrt/issues/1139).

**Commit 5 — `SMRT_STRICT_REGISTRY` default-on** ([ede3cc34](https://github.com/happyvertical/smrt/pull/new/refactor/issue-1134-collision-policy-strict-default/commits/ede3cc34))
Severity-`'error'` diagnostics now throw at record time by default. Four codes affected: `MANIFEST_EXPORT_INVALID`, `MANIFEST_EXPORT_NOT_JSON`, `MANIFEST_EXPORT_NOT_FOUND`, `PACKAGE_MANIFEST_READ_FAILED`. Warn-severity codes unchanged. Opt-out: `SMRT_STRICT_REGISTRY=false`. One test (`register-package-manifest.test.ts::silently no-ops when the manifest is malformed JSON`) rewritten to expect a throw; a new opt-out test verifies `=false` restores the legacy behavior and keeps the diagnostic collected.

**Commit 6 — Changeset** ([3ec82c42](https://github.com/happyvertical/smrt/pull/new/refactor/issue-1134-collision-policy-strict-default/commits/3ec82c42))
Minor release on `@happyvertical/smrt-core`.

## Verification

- **Local**: `npx turbo build` 41/41 · `npx turbo test` 80/80 · smrt-core unit tests 1563/1563 pass (baseline 1539 + 24 new: 23 collision-policy rows + 1 strict-mode opt-out)
- **Parity**: every issue-specific collision test (#531, #555, #584, #847, #950, #951, #1000) passes unmodified

## Breaking changes

Minor. Two breaking flips:

| Change | Migration |
|---|---|
| `SMRT_STRICT_REGISTRY` default on | Fix the underlying manifest issue **or** set `SMRT_STRICT_REGISTRY=false` |
| `SMRT_SKIP_STI_REHYDRATE` removed | Remove the flag from your env; it's now a no-op |

Error message text is unchanged; the verbose-log output now includes a stable scenario id from the decision table.

## Review feedback addressed

All four points from the [Codex plan review](https://github.com/happyvertical/smrt/issues/1134#issuecomment-4290823035):

1. **§4 scope narrowed** — flag goes, rehydration loop stays; the `external-runtime-hydration.test.ts:1071` contract is preserved.
2. **`merge-manifest` caller contract documented** — the `applyManifestCollisionPolicy` branch in `class-registration.ts` calls `mergeManifestIntoExistingRegistration` then conditionally aliases the qualified key. `issue-951:144-200` verifies both steps.
3. **Invocation contract made explicit** — `decideCollisionPolicy`'s docstring calls out that ambiguous simple-name matches (multiple packages) must NOT be fed through the table. Caller-side handles the no-candidate and ambiguous-candidate cases.
4. **Diagnostic call-site count corrected** — 6 total (4 error, 2 warn), not 7. Test audit identified one test needing an opt-out stub; handled in commit 5.

## Test plan

- [x] Build all packages green (41/41)
- [x] Full test suite green (80/80 tasks, 1563 core tests)
- [x] Every row in the collision-policy table has a dedicated unit test
- [x] Every issue-specific collision test (531/555/584/847/950/951/1000) passes unmodified
- [x] `external-runtime-hydration.test.ts:1071` stale-cache repair test passes without the env flag
- [x] Strict-mode throws on malformed JSON; opt-out restores permissive behavior
- [ ] CI parity on PR

### CODE REVIEW

File: packages/core/src/registry/collision-policy.ts [hunk 1]
```diff
@@ -0,0 +1,392 @@
...
+      'Existing entry is the STI child of the incoming manifest parent; keep the child.',
+  },
+
+  {
+    scenario: 'manifest-different-packages-qualified-coexist',
+    match: (i) =>
+      i.origin === 'manifest' &&
+      !i.samePackage &&
+      i.hasNewQualifiedKey &&
+      i.existingIsPackageQualified,
```
Comment (willgriffin) [inline packages/core/src/registry/collision-policy.ts]: [P2] This narrows cross-package coexistence compared with the old manifest path. Before this refactor, `allowCoexistingQualifiedRegistration` only required both package names to be present and different; it did not require the existing package to be scoped. `createQualifiedName()` still happily builds `packageName:ClassName` for unscoped package ids, and this repo already registers manifests with unscoped names like `smrt-profiles`. With the new `existingIsPackageQualified` gate, a second unscoped package that defines the same simple class name now falls through to `manifest-default-skip`, silently dropping the registration instead of coexisting.

File: packages/core/src/registry/collision-policy.ts [hunk 2]
```diff
@@ -0,0 +1,392 @@
...
+    //   (b) `existingHasNoPackage` — source registration hasn't been
+    //       promoted to a qualified key yet and a manifest now provides
+    //       the package identity (issue #951:144-200). The merge runs
+    //       AND the caller aliases the existing entry under the new
+    //       qualified key.
+    scenario: 'manifest-same-package-merge',
+    match: (i) =>
+      i.origin === 'manifest' &&
+      (i.samePackage || (i.existingHasNoPackage && i.hasNewQualifiedKey)) &&
+      !i.existingIsManifestStub &&
```
Comment (willgriffin) [inline packages/core/src/registry/collision-policy.ts]: [P1] The `existingHasNoPackage` promotion path no longer covers manifest-first registrations. `registerFromManifest()` always creates a manifest stub, so when an unqualified/local manifest seeds `ClassName` first and a later package-qualified manifest for that same class arrives, this row does not match because of `!i.existingIsManifestStub`. The flow falls through to `manifest-default-skip`, so the later package identity and any richer schema/validationRules never merge or alias under `@pkg:ClassName`. Pre-Release-C, the corresponding branch merged whenever `!existing.packageName || packageName === existing.packageName`, regardless of stub status.

**Comment by willgriffin** [comment]
All three inline comments plus a deep-review pass from two subagents addressed in [1aa44cc0](https://github.com/happyvertical/smrt/pull/1140/commits/1aa44cc0).

### Correctness fixes

**P1 Copilot — `hasNewQualifiedKey` derivation** ([class-registration.ts:287](packages/core/src/registry/class-registration.ts:287))
Switched to `isQualifiedName(registrationKey)`. Now covers the `objectDef.qualifiedName` fallback path that bypasses `packageName`.

**P2 willgriffin — `existingIsPackageQualified` too narrow** ([collision-policy.ts:251](packages/core/src/registry/collision-policy.ts:251))
Added `existingHasAnyPackage: boolean` to `CollisionInputs`. The `manifest-different-packages-qualified-coexist` row and the `decorator-case-insensitive-pnpm-duplicate` row both use the broader semantic. Unscoped package names (`smrt-profiles`, etc.) now coexist instead of falling through to skip. Dedicated unit test added at `collision-policy.test.ts`.

**P1 willgriffin — stub-upgrade blocked by `!existingIsManifestStub`** ([collision-policy.ts:270](packages/core/src/registry/collision-policy.ts:270))
Removed the gate. The `manifest-same-package-merge` row now fires for stub-upgrade cases too, matching pre-Release-C behavior where merge ran whenever `packageName === existing.packageName || !existing.packageName`. Dedicated unit test added.

### Additional findings from a parallel subagent review

**Correctness — `existingExtendsNew` missing `registrationKey` comparison** ([class-registration.ts:260](packages/core/src/registry/class-registration.ts:260))
Symmetric to `newExtendsExisting`, which already includes the check. Caught a case where a child's `existing.extends` stores a qualified parent key post-`qualifyExtendsName()` and the parent manifest then arrives again — pre-fix would register a duplicate parent instead of skipping. New regression test at `issue-950-manifest-sti-collision.test.ts`.

**Migration — thrown error message opt-out hint** ([diagnostics.ts:87](packages/core/src/registry/diagnostics.ts:87))
Appended ` — set SMRT_STRICT_REGISTRY=false to record this diagnostic without throwing.` The hint is load-bearing because `PACKAGE_MANIFEST_READ_FAILED` can propagate out of a `__smrt-register__.ts` top-level side effect at module import time — before any consumer code has a chance to run. Without the hint, the crash has no visible recovery path.

**Migration — deprecation warn for `SMRT_SKIP_STI_REHYDRATE`** ([object.ts:83](packages/core/src/object.ts:83))
One-shot warn fires the first time an STI `save()` runs with the env var set. Anyone who followed the Release A changeset guidance and set the flag now discovers it's been retired instead of silently losing the behavior they wanted.

**Coverage — `MANIFEST_EXPORT_*` codes had no tests** (new file `strict-registry-manifest-export-errors.test.ts`)
Each of the three codes now has both a throw-path test and an `SMRT_STRICT_REGISTRY=false` opt-out-path test, plus a dedicated check that the thrown error message includes the opt-out hint. 7 tests total.

### Verification

- 1573/1573 core tests pass (baseline 1563 + 10 new)
- `npx turbo test` — 80/80 tasks green
- Every decision-table row still has a named scenario test; the three new scenarios (unscoped coexist, stub-upgrade merge, qualified-extends STI parent-skip) each have explicit coverage
